package com.BugTracking;
// Generated 30 May, 2018 6:17:26 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name = "event", catalog = "bt2")
public class Event implements java.io.Serializable {

	private long eventId;
	private String duration;
	private String eventTitle;
	private String location;
	private Date scheduleOn;
	private String startTime;
	private Set admins = new HashSet(0);
	private Set users = new HashSet(0);

	public Event() {
	}

	public Event(long eventId) {
		this.eventId = eventId;
	}

	public Event(long eventId, String duration, String eventTitle, String location, Date scheduleOn, String startTime,
			Set admins, Set users) {
		this.eventId = eventId;
		this.duration = duration;
		this.eventTitle = eventTitle;
		this.location = location;
		this.scheduleOn = scheduleOn;
		this.startTime = startTime;
		this.admins = admins;
		this.users = users;
	}

	@Id

	@Column(name = "Event_ID", unique = true, nullable = false)
	public long getEventId() {
		return this.eventId;
	}

	public void setEventId(long eventId) {
		this.eventId = eventId;
	}

	@Column(name = "Duration")
	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	@Column(name = "Event_Title")
	public String getEventTitle() {
		return this.eventTitle;
	}

	public void setEventTitle(String eventTitle) {
		this.eventTitle = eventTitle;
	}

	@Column(name = "Location")
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Schedule_On", length = 19)
	public Date getScheduleOn() {
		return this.scheduleOn;
	}

	public void setScheduleOn(Date scheduleOn) {
		this.scheduleOn = scheduleOn;
	}

	@Column(name = "Start_Time")
	public String getStartTime() {
		return this.startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "event_admin", catalog = "bt2", joinColumns = {
			@JoinColumn(name = "Event_id_fk", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "admin_id_fk", nullable = false, updatable = false) })
	public Set getAdmins() {
		return this.admins;
	}

	public void setAdmins(Set admins) {
		this.admins = admins;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "event_user", catalog = "bt2", joinColumns = {
			@JoinColumn(name = "Event_id_fk", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "User_ID_FK", nullable = false, updatable = false) })
	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
