package com.BugTracking;
// Generated 30 May, 2018 6:17:26 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Flag generated by hbm2java
 */
@Entity
@Table(name = "flag", catalog = "bt2")
public class Flag implements java.io.Serializable {

	private long flagId;
	private Bug bug;
	private String flagType;

	public Flag() {
	}

	public Flag(long flagId) {
		this.flagId = flagId;
	}

	public Flag(long flagId, Bug bug, String flagType) {
		this.flagId = flagId;
		this.bug = bug;
		this.flagType = flagType;
	}

	@Id

	@Column(name = "Flag_ID", unique = true, nullable = false)
	public long getFlagId() {
		return this.flagId;
	}

	public void setFlagId(long flagId) {
		this.flagId = flagId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Bug_ID")
	public Bug getBug() {
		return this.bug;
	}

	public void setBug(Bug bug) {
		this.bug = bug;
	}

	@Column(name = "Flag_Type")
	public String getFlagType() {
		return this.flagType;
	}

	public void setFlagType(String flagType) {
		this.flagType = flagType;
	}

}
