package com.BugTracking;
// Generated 30 May, 2018 6:17:26 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Reproducible generated by hbm2java
 */
@Entity
@Table(name = "reproducible", catalog = "bt2")
public class Reproducible implements java.io.Serializable {

	private long reproduceId;
	private Bug bug;
	private String isItReproducible;

	public Reproducible() {
	}

	public Reproducible(long reproduceId) {
		this.reproduceId = reproduceId;
	}

	public Reproducible(long reproduceId, Bug bug, String isItReproducible) {
		this.reproduceId = reproduceId;
		this.bug = bug;
		this.isItReproducible = isItReproducible;
	}

	@Id

	@Column(name = "Reproduce_ID", unique = true, nullable = false)
	public long getReproduceId() {
		return this.reproduceId;
	}

	public void setReproduceId(long reproduceId) {
		this.reproduceId = reproduceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Bug_ID")
	public Bug getBug() {
		return this.bug;
	}

	public void setBug(Bug bug) {
		this.bug = bug;
	}

	@Column(name = "Is_It_Reproducible")
	public String getIsItReproducible() {
		return this.isItReproducible;
	}

	public void setIsItReproducible(String isItReproducible) {
		this.isItReproducible = isItReproducible;
	}

}
